services:
  # Backend API
  - type: web
    name: sitara777-admin-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false

  # Frontend Web App
  - type: web
    name: sitara777-admin-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://sitara777-admin-backend.onrender.com
    domains:
      - sitara777-admin.onrender.com